#!/bin/sh -e
CMD=$1

usage() {
  echo "Usage: $0 <command> <parameters>"
  echo "Commands can be:"
  echo " new appname"
  echo " start"
  echo " module install <name>"
  echo " module uninstall <name>"
}

if [ -z "$CMD" ]; then
  usage
  exit 1
fi

case "$CMD" in
  new)
    APPNAME=$2
    if [ -z "$APPNAME" ]; then
      echo "appname is empty"
      echo "Usage: $0 new appname"
      exit 1
    fi
    echo "Creating new hoodie app '$APPNAME'"
    git clone git://github.com/hoodiehq/my-first-hoodie.git $APPNAME
    cd $APPNAME
    PATTERN="s,{{hoodie_appname}},$APPNAME,g"
    perl -pi -e $PATTERN www/index.html package.json
    npm install
  ;;

  start)
    npm start
  ;;

  module|modules)
    ACTION=$2
    if [ -z "$ACTION" ]; then
      echo "What should I do?"
      exit 2
    fi
    case "$ACTION" in
      install)
        NAME=$3
        if [ -z "$NAME" ]; then
          echo "What module should I install?"
          exit 3
        fi
        npm install --save git://github.com/hoodiehq/worker-$NAME.git
        echo "Module $NAME installed successfully."
      ;;

      uninstall)
        NAME=$3
        if [ -z "$NAME" ]; then
          echo "What module should I uninstall?"
          exit 3
        fi
        npm uninstall --save hoodie-worker-$NAME
        echo "Module $NAME uninstalled successfully."
      ;;

      *)
        echo "Usage: $0 module uninstall <workername>"
        exit 4
      ;;
    esac
  ;;

  *)
  echo "$0 Unknown Command"
  echo
  usage
  exit 1
  ;;
esac
